Bugfix/load full gallery
salesfire/magento1 pull request #5
Opened 2020-02-10 11:41 UTC by Jamstaz

2020-02-12 13:52 UTC, StephenHonor requested changes

2020-02-12 13:52 UTC, StephenHonor commented on app/code/community/Salesfire/Salesfire/Model/Feed.php
> +        $backendModel = $collection->getResource()->getAttribute('media_gallery')->getBackend();
Is it possible to change this so it only does it when it needs to for the product?

2020-02-12 15:17 UTC, Jamstaz commented on app/code/community/Salesfire/Salesfire/Model/Feed.php
> +        $backendModel = $collection->getResource()->getAttribute('media_gallery')->getBackend();
Yes.

2020-02-13 11:47 UTC, elliotlings approved these changes

2020-02-14 19:49 UTC, StephenHonor approved these changes

2020-02-14 19:49 UTC, merged