[ch2000] Add CDATA to link and brand attributes.
salesfire/magento1 pull request #6
Opened 2020-09-15 16:09 UTC by Jamstaz

2020-09-15 16:12 UTC, elliotlings approved these changes

2020-09-15 16:13 UTC, elliotlings requested changes
Do we need to bump file versions and config version?

2020-09-16 08:35 UTC, Jamstaz commented
> Do we need to bump file versions and config version?

Yes. Bumped versions.

2020-09-16 08:56 UTC, alexhiggins submitted a review, later dismissed

2020-09-16 10:35 UTC, elliotlings approved these changes

2020-09-16 10:47 UTC, alexhiggins approved these changes

2020-09-16 10:48 UTC, merged